name: List Sponsors

on:
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read

jobs:
  list-sponsors:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: "24"

      - name: Install dependencies
        run: npm i --ignore-scripts

      - name: List sponsors
        env:
          GITHUB_TOKEN: ${{ secrets.SPONSOR_TOKEN }}
        run: node index.js sponsors --org fastify
